blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ è®¨è®ºåŒº
    url: https://github.com/AptS-1547/WeAreESAP/discussions
    about: æœ‰é—®é¢˜æˆ–æƒ³æ³•ï¼Ÿæ¥è®¨è®ºåŒºèŠèŠå§
  - name: ğŸ“š é¡¹ç›®æ–‡æ¡£
    url: https://weare.esaps.net
    about: è®¿é—®å®˜æ–¹ç½‘ç«™äº†è§£æ›´å¤šå…³äº ESAP çš„ä¿¡æ¯
